sudo: false
language: python
matrix:
  include:
    - python: "3.5"
      env: TOX_ENV=py35
    - python: "3.6"
      env: TOX_ENV=py36
    - python: "pypy3.5"
      env: TOX_ENV=pypy3
    - python: "3.6"
      env: TOX_ENV=lint
cache:
  - pip: true
  - directories:
    - $TRAVIS_BUILD_DIR/.hypothesis
install:
  - "travis_retry pip install pip setuptools --upgrade"
  - "travis_retry pip install tox"
before_script:
  - pip freeze
script:
  - tox -e $TOX_ENV
after_script:
  - cat .tox/$TOX_ENV/log/*.log
