version: 2.1

# heavily inspired by https://raw.githubusercontent.com/pinax/pinax-wiki/6bd2a99ab6f702e300d708532a6d1d9aa638b9f8/.circleci/config.yml

common: &common
  working_directory: ~/repo
  steps:
    - checkout
    - restore_cache:
        keys:
          - cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}
    - run:
        name: install dependencies
        command: pip install --user tox
    - run:
        name: run tox
        command: python -m tox -r
    - save_cache:
        paths:
          - .tox
          - ~/.cache/pip
          - ~/.local
          - ./eggs
        key: cache-{{ .Environment.CIRCLE_JOB }}-{{ checksum "setup.py" }}-{{ checksum "tox.ini" }}

jobs:
  lint:
    <<: *common
    docker:
      - image: cimg/python:3.7
    environment:
      TOXENV: lint

  py37-core:
    <<: *common
    docker:
      - image: cimg/python:3.7
    environment:
      TOXENV: py37

  py38-core:
    <<: *common
    docker:
      - image: cimg/python:3.8
    environment:
      TOXENV: py38

  py39-core:
    <<: *common
    docker:
      - image: cimg/python:3.9
    environment:
      TOXENV: py39

  py310-core:
    <<: *common
    docker:
      - image: cimg/python:3.10
    environment:
      TOXENV: py310

  py311-core:
    <<: *common
    docker:
      - image: cimg/python:3.11
    environment:
      TOXENV: py311

  pypy3-core:
    <<: *common
    docker:
      - image: pypy
    environment:
      TOXENV: pypy3

workflows:
  version: 2
  test:
    jobs:
      - lint
      - py37-core
      - py38-core
      - py39-core
      - py310-core
      - py311-core
      - pypy3-core
